#!/bin/sh

qsub -v MODEL=nordic32,EXP=baseline,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=baseline,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.no-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.no-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.no-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.no-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d1,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=baseline,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.no-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.no-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.no-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.no-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.yearly-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.one-channel.monthly-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.no-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.no-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.no-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.no-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.yearly-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.yearly-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.yearly-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.yearly-inspections.generators,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.monthly-inspections.all,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.monthly-inspections.lines,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.monthly-inspections.loads,N=300 job.sh
qsub -v MODEL=nordic32d2,EXP=breaker.attacker-weekly.two-channel.monthly-inspections.generators,N=300 job.sh
